#!/usr/bin/env python
import tests.dirty_series as ds
import helpers.input_validators as iv
import argparse
import pdb

def parse_args():
    descr = 'Generates noisy periodical test series'
    parser = argparse.ArgumentParser(description=descr)
    parser.add_argument(
        '-o',
        required = True,
        help='output file location, results is written to the specified text file in two columns: time, value',
        metavar='OUTPUT'
    )
    parser.add_argument(
        '-l',
        required = True,
        help='time series length',
        metavar='SERIES_LENGTH',
        type = iv.check_positive_int
    )
    parser.add_argument(
        '-t',
        required = True,
        help='maximum time value',
        metavar='TIME_VAL',
        type = iv.check_positive_float
    )
    parser.add_argument(
        '-p',
        required = True,
        help='periods to generate periodical series, number of args must be the same as for shifts',
        metavar='PERIODS',
        type = iv.check_positive_float,
        nargs='+'
    )
    parser.add_argument(
        '-d',
        required = True,
        help='shifts for respective periods to generate periodical series, number of args must be the same as for periods',
        metavar='SHIFTS',
        type = iv.check_positive_float,
        nargs='+'
    )
    parser.add_argument(
        '-s',
        required = True,
        help='sigma for normal distribution (to generate noise)',
        metavar='SIGMA',
        type = iv.check_positive_float
    )
    args = parser.parse_args()
    return args

def generate_series(args):
    """generate the series"""
    result = ds.generate_dirty_periodical_series_with_random_time_grid(
        args.l,
        args.t,
        args.p,
        args.d,
        args.s
    )
    return result

def save_series(series, file_path):
    """save seriess to the file """
    length = series[0].shape[0]
    file = open(file_path, "w")
    for i in range(0, length):
        # time and value
        string = '%e %e' % (series[0][i][0], series[1][i][0])
        print(string, file=file)
    file.close

def main():
    """entry point"""
    args = parse_args()
    series = generate_series(args)
    save_series(series, args.o)

main()